### ISSUE TITLE
把Queue的管理方式改成Map

### ISSUE THREAD

**Issue by wolf-yuan-6115** [B-l-u-e-b-e-r-r-y/Discord-Bot-02#6]

**Comment by B-l-u-e-b-e-r-r-y** [comment]
感謝提醒，我沒有用過 Map，剛剛去爬文後覺得是個很方便的東西，的確蠻適合用在這個案例 XD
目前這個 repository 就當成教學用，除非有 Bug 不然不會特地更新，以後會考慮出一隻功能比較完整的音樂機器人，到時候再來改寫囉~

**Comment by wolf-yuan-6115** [comment]
因為我自己有寫一個機器人，用Map真的比較方便

**Comment by wolf-yuan-6115** [comment]
噢對了
原始碼在這 https://github.com/Discord-cat-dev/blackcat

**Comment by B-l-u-e-b-e-r-r-y** [comment]
@wolf-yuan-6115  
很讚耶～～有蠻多可以參考的地方
⭐一個

**Comment by wolf-yuan-6115** [comment]
⭐

**Comment by B-l-u-e-b-e-r-r-y** [comment]
deprecated
